Create table Image (
	image_id Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	image_author Varchar(25) NOT NULL,
	url Varchar(600) NOT NULL,
	name Varchar(600),
	created Datetime,
	updated Datetime,
 Primary Key (image_id));

Create table Author (
	user_name Varchar(25) NOT NULL,
	registered Date NOT NULL,
 Primary Key (user_name));


Create table Tag (
	tag Varchar(16) NOT NULL,
	image_id Int NOT NULL,
 Primary Key (tag,image_id));


Create table Comment (
	comment_id Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	image_id Int NOT NULL,
	comment_author Varchar(25) NOT NULL,
	created Datetime NOT NULL,
	updated Datetime,
	comment_text Varchar(600) NOT NULL,
 Primary Key (comment_id));


Create table ImageRating (
	image_id Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	image_rating_author Varchar(25) NOT NULL,
	value Int NOT NULL,
 Primary Key (image_id,image_rating_author));


Create table CommentRating (
	comment_id Int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
	comment_rating_author Varchar(25) NOT NULL,
	value Int NOT NULL,
 Primary Key (comment_id,comment_rating_author));



Alter table Tag add Foreign Key (image_id) references Image (image_id) on delete  restrict on update  restrict;
Alter table Comment add Foreign Key (image_id) references Image (image_id) on delete  restrict on update  restrict;
Alter table ImageRating add Foreign Key (image_id) references Image (image_id) on delete  restrict on update  restrict;
Alter table Image add Foreign Key (image_author) references Author (user_name) on delete  restrict on update  restrict;
Alter table Comment add Foreign Key (comment_author) references Author (user_name) on delete  restrict on update  restrict;
Alter table ImageRating add Foreign Key (image_rating_author) references Author (user_name) on delete  restrict on update  restrict;
Alter table CommentRating add Foreign Key (comment_rating_author) references Author (user_name) on delete  restrict on update  restrict;
Alter table CommentRating add Foreign Key (comment_id) references Comment (comment_id) on delete  restrict on update  restrict;


Create trigger update_image
Before update on Image
Referencing NEW ROW AS new
For each row
SET new.updated=NOW()



Create trigger update_comment
Before update on Comment
Referencing NEW ROW AS new
For each row
SET new.updated=NOW()


Create trigger insert_image
Before insert on Image
Referencing NEW ROW AS new
For each row
SET new.created=NOW()


Create trigger insert_comment
Before insert on Comment
Referencing NEW ROW AS new
For each row
SET new.created=NOW()


Create trigger insert_author
Before insert on Author
Referencing NEW ROW AS new
For each row
SET new.registered=NOW()
